[package]
name = "aoc-solver-derive"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
core.workspace = true
itertools.workspace = true
syn = { version = "2.0.41", features = ["full"] }
quote = "1.0.33"
