[package]
name = "aoc-solver-derive"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.41", features = ["full"] }
proc-macro2 = "1.0.70"
quote = "1.0.33"
once_cell = "1.19.0"
