[package]
name = "aoc_2023_01"
version.workspace = true
edition.workspace = true
authors.workspace = true

[[bin]]
name = "2023_01"
path = "src/main.rs"

[dependencies]
core.workspace = true
core.intertools = true
aoc-solver-derive.workspace = true
